name: CI/CD Infra SQS - Fase5

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - 'infra/**'
      - '.github/workflows/**'
      - 'README.md'

permissions:
  contents: write
  pull-requests: write

jobs:
  validate:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - run: terraform init
      - run: terraform plan -out=tfplan -no-color
      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/tfplan

  open-pr:
    name: Open Pull Request
    needs: validate
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head ${{ github.ref_name }} \
            --title "Auto PR: Infra SQS Fase5 - ${{ github.ref_name }}" \
            --body "PR criado automaticamente após sucesso no Terraform Plan." \
            || echo "PR já existe ou não pôde ser criado."

  deploy:
    name: Terraform Apply
    needs: validate
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - run: terraform init
      - uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: infra
      - run: terraform apply -auto-approve tfplan
      - run: |
          terraform output catalog_queue_url || true
          terraform output os_queue_url || true
